name: Build and Upload Package

on:
  - push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Build Tools
        run: python -m pip install --upgrade pip build

      - name: Build Package
        run: python -m build  # Uses PEP 517 to build the package

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz  # Upload the `.tar.gz` file as a source distribution
          token: ${{ secrets.GITHUB_TOKEN }}
